### ISSUE TITLE
Cannot be used in password input fields

### ISSUE THREAD

**Issue by jgosmann** [jgosmann/neo2-layout-osx#1]
This works with the original layout file. It is not clear to me why it does not work with the modified file.

Incomplete list of potential differences causing this:
* The updated file is XML 1.1 instead of 1.0
* The keyboard group tag is set to 126 instead of 0
* ...?

**Comment by neominik** [comment]
I noticed that writing capital letters is quite broken with this layout. Trying to write the alphabet:
AbcdEfghIjklmNOpqrstUvwxYZ
That was why I couldn't use it for password fields^^

**Comment by jgosmann** [comment]
That's a different issue, that should luckily be somewhat easy to fix (just a bit tedious).

**Comment by PaulePan** [comment]
>  Trying to write the alphabet: AbcdEfghIjklmNOpqrstUvwxYZ

I have the same Issue

**Comment by jgosmann** [comment]
The capitalization issue should be fixed. The actual problem I opened this issue for seems to be resolved too. I will use the keyboard layout file a bit more and see if the problem reoccurs and if not I'll close this issue.
