### ISSUE TITLE
Dvorak Neo cross over

### ISSUE THREAD

**Issue by homoroselaps** [jgosmann/neo2-layout-osx#10]
Hi,
some time ago I adopted the Neo windows driver to write Dvorak on the first two layers.
Now I switched to Mac and started adopting your keylayout file accordingly, but run into some difficulties that I can't wrap my head around. Could you give me some tips and tricks how to accomplish the Dvorak modification?

Here is what I tried so far:
- I used ukelele to change the keys, but the end result was quite broken.
- I started changing the keymap index0 & index1 of the keylayout file by hand, with good results. But any commands such as Cmd+F are not yet working (I still have to press the Neo keys and I don't know why).

An overview of the interplay between KarabinerElements and the 9 different keyMaps of the keyboard layout may help me.
All the best

**Comment by jgosmann** [comment]
`Cmd` is treated as its own modifier key with its own separate layer/key layout. You can see all layers in Ukelele in the “Modifiers” tab. You probably want to adjust layer 7 (defined as `Alt`/option not pressed and `Cmd` pressed). Either in Ukelele or by hand in the XML file.

KarabinerElements does the following things in addition to the keyboard layout file (that cannot be done with the keyboard layout file alone):

* Map additional modifier keys that are not modifier keys in traditional keyboard layouts.
* Implement layer 4
  * map from individual keys (when pressed with mod4)
    * to special keys such as arrow keys
    * to special characters (such as ªº№» etc.) via a multi-key sequence that uses dead keys (first key press is `alt+shift+z` activating dead key state and the original key press gets reproduced which then produces the desired character due to the dead key state)
    * to key combinations (such as `cmd+left` for `mod4+s`)
* Implement layer 6 with dead keys as analogous to the layer 4

Keys above are given as on the qwerty layout. Note the Karabiner Elements does the mapping based on the actual keycode, thus before the keyboard layout converts the keycode to the actual character (or action) produced.

Hope that helps.

**Comment by homoroselaps** [comment]
Thanks so much for the quick answer and overview. I translated the keylayout file another time completely manually. (layout 0,1,2,3,7).
[dvorak_neo.keylayout.txt](https://github.com/jgosmann/neo2-layout-osx/files/2876433/dvorak_neo.keylayout.txt)

The issue remains, but now I can make it more specific: The command keys are not working in every app the same way.
If no cmd key is pressed  the "z" key (printed letter z on qwertz layout) is recognized as "f" (correct dvorak) in chrome as well as firefox.
If pressed with cmd, chrome receives an "f" (dvorak) were as firefox receives a "k" (neo).
The same with all other keys. Apps like Chrome, VSCode, PyCharm, iTerm receive my updated Dvorak keys when pressed in combination with Cmd. Firefox and Finder receive the neo variant.
(Karabiner is deactivated for all tests, I run Mojave 10.14.3)

**Comment by homoroselaps** [comment]
-> A reboot fixed the problem for now \o/

**Comment by jgosmann** [comment]
Sometimes applications do not respect the keyboard layout for shortcuts, but look at the keycode (see #6). But great, that it works now!
