### ISSUE TITLE
Not appearing as input source for MacOS Catalina

### ISSUE THREAD

**Issue by dsc8x** [jgosmann/neo2-layout-osx#11]
Hey :)

I copied the `.keylayout` and the `.icns` to `/Library/Keyboard Layouts/` and rebooted the computer.

Unfortunately the layout does not appear in the input sources dialog. Did you successfully make it work with Catalina yet?

**Comment by dsc8x** [comment]
Never mind, a `chmod 777` fixed it 👍

**Comment by jgosmann** [comment]
`chmod 777` should not be required and gives more permissions to the files than you might want. `chmod 644` should be sufficient and works for me on Catalina.

**Comment by dsc8x** [comment]
True, I just didn't care too much about it, as I'm the only user on my macbook and not much harm can be done by changing the keylayout files anyways. But of course, you're right and read perms are enough ;)
