### ISSUE TITLE
JetBrains IDE workaround stopped working

### ISSUE THREAD

**Issue by jaylinski** [jgosmann/neo2-layout-osx#15]
Hi! I just upgraded to PhpStorm 2020.2, and now the workaround `com.jetbrains.use.old.keyevent.processing=true` stopped working.
I'm now getting weird output when typing Mod3 chars in the Terminal.

Is there another workaround? The ticket https://youtrack.jetbrains.com/issue/JBR-1311 doesn't provide any useful solution for my problem...

(Thanks for this awesome repo!)

**Comment by jgosmann** [comment]
That is weird. I'm not using PhpStorm, but IntelliJ 2020.2 at work and I'm not having any issues. Did you double check the workaround wasn't somehow overwritten?

Unfortunately, I do not know of any other workarounds.

**Comment by jaylinski** [comment]
Nope, wasn't overwritten. Also I have no idea why this only happens in the Intellij terminal, but works fine in the editor... 🤔

**Comment by jgosmann** [comment]
I missed that this is only in the Terminal ... I rarely use the IntelliJ-Terminal, but I do have the same problem there.

**Comment by jaylinski** [comment]
The "fix" is to disable the

* `Prevent problematic keys (?, /, #, =, and ')') from being treated as option key shortcut `
* `Prevent all layer 3 keys from being treated as option key shortcut`

Karabiner modifications.

**Comment by jgosmann** [comment]
Good to know! I added a comment to the README about that.

Unfortunately, I don't see a way to make things work in all programs at the same time. Thus, you have the option to at least chose ...
