### ISSUE TITLE
Prevent shortcut keys layer 3 disables layer 3 for these keys entirely

### ISSUE THREAD

**Issue by olbrichj** [jgosmann/neo2-layout-osx#16]
Hey,
In a few code editors (e.g. leetcode) within browsers (Chrome and Firefox, not Safari) I can not type = or :. There might me more keys but I didn't find any yet.
= is interpreted as jump to end of line
: is interpreted as delete all characters after the cursor.

I don't have any "Prevent keys from being treated as option key shortcut" rules active as it just deactivates those keys interely and I can't type = or : anywhere within macOS -.-

Any idea other than changing my browser to fix this?

my config:
[karabiner.txt](https://github.com/jgosmann/neo2-layout-osx/files/5398208/karabiner.txt)

**Comment by jgosmann** [comment]
You will need to activate "Prevent keys from being treated as option key shortcut", also make sure to use the keyboard layout file from this repository.

**Comment by olbrichj** [comment]
I didn't use the keyboard layout file from thes repository 🤦 
Thanks for the help
