### ISSUE TITLE
Mod4 lockt Automatisch

### ISSUE THREAD

**Issue by ghost** [jgosmann/neo2-layout-osx#17]
Hi! Da mir die lieben Leute im Chat nicht helfen können hoffe ich auf dich. Ich musste Neo2 auf meinen Mac erneut installieren und seit dem habe ich das Problem, dass sich mod4 immer toggelt und dann bleibt, bis die Mod4 keys erneut gedrückt werden. Das passiert bei beiden Mod4-Keys und das ist leider sehr störend im Fluss, wenn man die Mod4 Ebene viel nutzt wie ich. 

Ich habe sowohl die letzte Neo Version versucht, als auch die neuste. Die Regeln in Karabiner Elements habe ich genauso installiert und auch alles erneut installiert. Dieses Problem bleibt leider. 

Ich vermute dass es an den Regeln liegt, aber ich kenne mich damit leider null aus. 

LG 

Catalina 10.15.7

**Comment by jgosmann** [comment]
Vermutlich durch pqrs-org/KE-complex_modifications#747 hervorgerufen. Leider muss ich mir das auch erst genauer anschauen, wird aber vermutlich etwas dauern bis ich dazu komme.

**Comment by christophebeling** [comment]
Der gleiche Fehler triff bei mir auch auf. @jgosmann falls du irgendwelche Logs benötigst gib gerne bescheid.

**Comment by Matzkowsky** [comment]
Tut mir leid wenn ich mit meiner Änderung Verwirrung gestiftet habe. Ich hatte den PR damals eigentlich eher zur Diskussion gestellt. Er wurde dann aber innerhalb eines Tages gemerged. Ich arbeite an einer Lösung…

**Comment by christophebeling** [comment]
Gibt es hier Neuigkeiten?

**Comment by ghost** [comment]
Würde mich auch interessieren :) Danke für eure Hilfe schonmal!

**Comment by Matzkowsky** [comment]
Hallo miteinander. Ich habe eine Lösung gefunden die konsistent zur Linux Implementierung ist. Durch simultanes drücken beider mod4 Tasten wird der Modus 4 nun ein und aus geschaltet. Ich würde mich freuen wenn ihr das mal ausprobieren und mir Rückmeldung geben könntet. Bei meiner letzten Änderung hat der Maintainer das umgehend gemerged obwohl ich das gern erst mit den Neo2-Nutzern diskutiert hätte. Hier der Link zum [PR](https://github.com/pqrs-org/KE-complex_modifications/pull/777). Sobald der gemerged ist, solltet ihr die neuen Regeln durch erneuten Import von https://ke-complex-modifications.pqrs.org#neo2 ausprobieren können.
Falls ihr die Regeln vorher ausprobieren möchtet, kann ich Euch das neo2.json auch gern vorab zum Testen schicken.

**Comment by christophebeling** [comment]
@Matzkowsky Vielen Dank - das klingt sehr gut. Ich würde gerne vorab testen.

**Comment by Matzkowsky** [comment]
@christophebeling bitte sehr. Die Datei entpacken und unter ~/.config/karabiner/assets/complex_modifications/ ablegen und Karabiner Elements müsste diese bei den Complex Modifications auflisten
[neo2.json.zip](https://github.com/jgosmann/neo2-layout-osx/files/5546386/neo2.json.zip)

**Comment by ghost** [comment]
Hi, vielen lieben Dank für deine Bemühungen. Mit dem Reimport hat es bei mir auch nach mehreren Versuchen nicht funktioniert. Aber mit dem manuellen import jetzt funktioniert es Problemlos. Danke!!

**Comment by jgosmann** [comment]
Die Regeln auf der Webseite wurden zunächst nicht aktualisiert (aufgrund eines anderen Problems), sollten jetzt aber aktuell sein. Ich schließe das Ticket dann mal, wenn es noch Probleme gibt gerne wieder öffnen.
