### ISSUE TITLE
Ganze Wörter springen

### ISSUE THREAD

**Issue by pibebtol** [jgosmann/neo2-layout-osx#18]
Hi,
ich bin kürzlich auf Mac umgestiegen und mir fehlt im Neo2 Layout hier die Möglichkeit über die Pfeiltasten der 4ten Ebene in Verbindung mit Steuerung (auf Windows und Linux) oder alt (oder option unter Mac) ein ganzes Wort zu springen/löschen/markieren.
Hat dafür zufällig jemand eine Lösung gefunden, bzw wie geht ihr damit um?

Vielleicht noch zur Verdeutlichung:
* wenn ich Caps+i tippe, kommt "/" wie erwartet
* Caps+Left springt ein Wort nach links
* Caps+<+i schreibt "/", gewünscht wäre aber auch Wort nach links

Über Lösungsvorschläge wäre ich sehr glücklich! 😄

**Comment by jgosmann** [comment]
<kbd>Mod3</kbd>+<kbd>Mod4</kbd> aktiviert in Neo2 die 6. Ebene, daher ist das mit den genannten Tasten so erstmal nicht möglich.

An sich sollte die linke untere <kbd>Alt</kbd>-Taste in Neo2 weiterhin eine <kbd>Alt</kbd> und keine <kbd>Mod3</kbd>-Taste sein, d.h. dann könnte man <kbd>Alt</kbd>+<kbd>Mod4</kbd>+<kbd>←</kbd> ein Wort nach links springen. Allerdings unterscheidet die Umsetzung des Layouts momentan nicht zwischen <kbd>Alt</kbd> und <kbd>Mod3</kbd>. Ich kann nochmal schauen, ob sich das ändern lässt, aber vermutlich ist das nicht ohne weiteres machbar.

**Comment by pibebtol** [comment]
Ok, vielen Dank für die Antwort! Hab schon vermutet, dass das nicht so einfach da ist, aber dachte, vielleicht gibt es da einen bekannten WorkAround... Wenn du was findest, sag bescheid :)

**Comment by jgosmann** [comment]
Ich habe jetzt die Neo2-Regeln für Karabiner Elements wie folgt geändert:

* <kbd>Caps Lock</kbd> und <kbd>#</kbd> werden immer auf <kbd>right_option</kbd> gemappt (vorher gemischt <kbd>left_option</kbd> und <kbd>right_option</kbd>, was als <kbd>Mod 3</kbd> fungiert. Zusammen mit <kbd>Mod 4</kbd> gelangt man so wie bisher auf die 6. Ebene.
* <kbd>left_option</kbd> wird weiterhin auf <kbd>left_option</kbd> gemappt, fungiert aber nicht mehr als <kbd>Mod 3</kbd>, d.h. <kbd>left_option</kbd>+<kbd>Mod 4</kbd> verbleibt auf der 4. Ebene, was es ermöglicht effektiv z.B. mit <kbd>Option</kbd>+<kbd>Mod 4</kbd>+<kbd>i</kbd> effektiv <kbd>Option</kbd>+<kbd>←</kbd> zu tippen.
* <kbd>left_option</kbd> aktiviert aber weiterhin die 3. Ebene. Das sollte es eigentlich nicht, aber hier sind Tasturlayouts in macOS technisch limitiert, da sie nicht zwischen <kbd>left_option</kbd> und <kbd>right_option</kbd> unterscheiden können. Abhänging vom Programm kann es aber sein, dass Tastenkombinationen mit <kbd>left_option</kbd> trotzdem wie auf der ersten Ebene interpretiert werden (womöglich ist das sogar der Regelfall und im Wesentlichen nur auf Webseiten im Browser wie Google Docs anders).

**Comment by pibebtol** [comment]
Vielen Dank für den Aufwand.
Das klingt nach einer guten Lösung, allerdings funktionieren die neuen Regeln bei mir nicht. Muss ich noch mehr machen, außer die Regeln neu zu importieren?

Edit: Nochmal etwas mehr Info:
Ich habe die Regeln jetzt aus dem Repo für die Karabiner-Regeln direkt per Hand importiert, aber das Verhalten mit `left_option`+`Mod4` ist immernoch wie vorher. Darf ich dafür die `left_opton`-Taste mit simplen Modifikationen umbelegen?

**Comment by jgosmann** [comment]
Die Regeln neu importieren, einmal alle aus der Liste der aktivierten Regeln löschen und neu aktivieren.

"Simple modifications" auf <kbd>left_option</kbd> können mit den anderen Regeln interferieren.

**Comment by pibebtol** [comment]
Habs alles nochmal ganz frisch gemacht und jetzt funktioniert es.

Vielen Dank für den Einsatz!
