### ISSUE TITLE
Change $ to €

### ISSUE THREAD

**Issue by PaulePan** [jgosmann/neo2-layout-osx#3]
I want to change Layer 3 + x (0x7) from $ to €. Is that possible?

**Comment by jgosmann** [comment]
You can edit the keyboard layout file with [Ukelele](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele&_sc=1) or change the $ in [lines like this](https://github.com/jgosmann/neo2-layout-osx/blob/master/neo.keylayout#L1669) with a text editor.

**Comment by PaulePan** [comment]
Worked with Ukelele. Thank you.
